### ISSUE TITLE
Create properties file loader

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#13]
### **Card** 
The service self registration library should be able to read a properties files from the project resource directory where the library is included. 

### **Discussion**
Provide marker interface to mark classes which hold properties values.
Properties values fields can be marked with custom annotation @ByValue(key = property key)

**Comment by RisteJovanoski** [comment]
To use this library first you need to add a dependency in pom.xml.
```
<repositories>
     <repository>
          <id>GitHub repository</id>
          <url>https://github.com/RisteJovanoski/maven-repositories/raw/maven-repositories</url>
     </repository>
</repositories>
```
```
<dependency>
     <groupId>com.github.emiovksa.mm.property.files.loader</groupId>
     <artifactId>properties.file.loader</artifactId>
     <version>0.0.1-SNAPSHOT</version>
</dependency>
```

Then you need to create a POJO class representing a .properties file.

Example:

```
@PropertiesResource("test.properties")
public class TestProperties {

    @PropertyName("resource.property.1")
    private String property;

    public String getProperty() {
        return property;
    }

    public void setProperty(String property) {
        this.property = property;
    }
}
```
After that you need to call `PropertiesFilesService.getPropertiesResource(YOUR_CLASS.class)` which returns the POJO representation of the .properties file.

Example:

```
TestProperties properties = PropertiesFilesService.getPropertiesResource(TestProperties.class);
properties.getProperty();

```
