### ISSUE TITLE
Make service self registration library available as maven dependency

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#14]
### **Card** 
The provided library should be available to the community via maven.

### **Acceptance criteria**

The library maven dependency is successfully included in another maven project

**Comment by RisteJovanoski** [comment]
To use this project as maven dependency if it is not deployed to GitHub as maven dependency, you need to deploy it. Follow [this](https://github.com/emiovska/microservices-monitoring/wiki/Configuration-for-maven-dependency-deployment) steps for deployment. After the project is successfully deployed you need to add this lines in the `pom.xml` file

```
<repositories>
     <repository>
          <id>GitHub repository</id>
          <url>https://github.com/RisteJovanoski/maven-repositories/raw/maven-repositories</url>
     </repository>
</repositories>
```

```
<dependency>
     <groupId>com.github.emiovska.mm.self.service.registration</groupId>
     <artifactId>mm.self.service.registration</artifactId>
     <version>0.0.1-SNAPSHOT</version>
</dependency>
```
