### ISSUE TITLE
Make service registrar library available as maven dependency

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#26]
### **Card** 

The provided library should be exposed as a maven dependency for further usage.
Maven deploy plugin should be configured.
**_Note_**: The same approach should be applied to self-service-registration module as well.

### **Discussion**
Create documentation for maven deploy plugin configuration. The documentation should be in wiki page.

### **Acceptance criteria**
The library can be include as dependency in another Maven project

**Comment by RisteJovanoski** [comment]
Link to documentation for configuration for deployment as maven dependency
https://github.com/emiovska/microservices-monitoring/wiki/Configuration-for-maven-dependency-deployment
