### ISSUE TITLE
Support configurable registration/deregistration endpoints

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#28]
### **Card** 

The user of the library should can configure the registration POST url endpoint and deregistration GET endpoint  in the service.registrar.properties file

**Comment by RisteJovanoski** [comment]
You need to create a `service.registrar.properties` file in the root of the resources folder. In that file you need to provide information about the endpoints. Property names that must be configured are the following:

- `registration.endpoint`
- `deregistration.endpoint`

Example:
```
registration.endpoint=/register
deregistration.endpoint=/deregister
```
