### ISSUE TITLE
Git and GitHub training

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#3]
### **Card** 
The following tutorials must be covered:

- [What is version control and Gitl](https://www.atlassian.com/git/tutorials/what-is-version-control)

- [Setup Git repository](https://www.atlassian.com/git/tutorials/setting-up-a-repository)

- [Git collaboration](https://www.atlassian.com/git/tutorials/syncing)

- [Git advanced overview](https://www.atlassian.com/git/tutorials/advanced-overview)

- [Contribution guidelines](https://github.com/blog/1184-contributing-guidelines)

 For further details how Git flow and concepts are implemented in GitHub see [GitHub help page](https://help.github.com/)

The contribution file about this repository is created on a root level of the project and is available on the following link [CONTRIBUTING.md](https://github.com/emiovska/microservices-monitoring/blob/master/CONTRIBUTING.md)

As a Git tool, the Intellij Git support should be used. For further details visit  [Intellij Git Integration](https://www.jetbrains.com/help/idea/2017.1/using-git-integration.html)

### **Acceptance criteria**

The developer is able to contribute to the repository using the Git flow and concepts

**Comment by RisteJovanoski** [comment]
Here is a link to the repository in which I practiced the git concepts:
https://github.com/RisteJovanoski/testingRepo
