### ISSUE TITLE
Setup notification mechanism about service state changes

### ISSUE THREAD

**Issue by emiovska** [emiovska/microservices-monitoring#34]
### **Card** 
The library should provide a mechanism to notify a clients (service/class) about service state changes.
After the registration request is received on the configured endpoint, the library should notify the subscribed clients about the received service changes. 

**_Note_**: The subscribers are actually classes from the project where the library is included. 

### **Discussion**
There are can be more than one subscribers about service changes. 
Think about which design pattern can be applied - **_Observer pattern_** (java implementation)

**Comment by RisteJovanoski** [comment]
Usage:

Implement the `ServiceSrtatusListener` where you need to handle when the event is called.

Register it to the `ServiceStatusNotifier` obtained through `ServiceStatusNotifierManager.getNotifier()`, call the `registerListener` method.

The listeners are notified when the notifier calls `notifyListeners`.
